import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:lucide_icons/lucide_icons.dart';
import '../../../app/providers.dart';
import '../../../core/theme.dart';
import '../../../core/widgets/async_state_widgets.dart';
class ReviewsScreen extends ConsumerStatefulWidget{const ReviewsScreen({super.key});@override ConsumerState<ReviewsScreen>createState()=>_ReviewsScreenState();}
class _ReviewsScreenState extends ConsumerState<ReviewsScreen>{List<Map<String,dynamic>>items=[];bool loading=true;@override void initState(){super.initState();_load();}Future<void>_load()async{if(mounted)setState(()=>loading=true);try{items=await ref.read(engagementRepositoryProvider).reviewable();}catch(e){if(mounted)showSpikeToast(context,e.toString());}finally{if(mounted)setState(()=>loading=false);}}Future<void>_rate({required bool store,required Map<String,dynamic>item})async{int rating=5;final comment=TextEditingController();final ok=await showModalBottomSheet<bool>(context:context,isScrollControlled:true,showDragHandle:true,builder:(sheet)=>StatefulBuilder(builder:(sheet,setLocal)=>Padding(padding:EdgeInsets.fromLTRB(20,4,20,MediaQuery.viewInsetsOf(sheet).bottom+22),child:Column(mainAxisSize:MainAxisSize.min,children:[Text(store?'تقييم المتجر':'تقييم المنتج',style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900)),const SizedBox(height:5),Text(store?'${item['store_name']??''}':'${item['product_name']??''}',style:const TextStyle(fontSize:11,color:spikeMuted)),const SizedBox(height:12),Row(mainAxisAlignment:MainAxisAlignment.center,children:List.generate(5,(i)=>IconButton(iconSize:32,onPressed:()=>setLocal(()=>rating=i+1),icon:Icon(i<rating?Icons.star_rounded:Icons.star_outline_rounded,color:Colors.amber))),),TextField(controller:comment,maxLines:3,decoration:const InputDecoration(hintText:'اكتب تعليقك (اختياري)',filled:true,fillColor:spikeField,border:OutlineInputBorder(borderSide:BorderSide.none,borderRadius:BorderRadius.all(Radius.circular(17))))),const SizedBox(height:12),SizedBox(width:double.infinity,height:48,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:spikeRed),onPressed:()=>Navigator.pop(sheet,true),child:const Text('إرسال التقييم',style:TextStyle(fontWeight:FontWeight.w900))))]))));if(ok!=true){comment.dispose();return;}try{final repo=ref.read(engagementRepositoryProvider);if(store){await repo.reviewStore(suborderId:'${item['suborder_id']}',rating:rating,comment:comment.text);}else{await repo.reviewProduct(orderItemId:'${item['order_item_id']}',rating:rating,comment:comment.text);}if(mounted){showSpikeToast(context,'تم إرسال تقييمك');await _load();}}catch(e){if(mounted)showSpikeToast(context,e.toString());}finally{comment.dispose();}}
@override Widget build(BuildContext context){final dark=Theme.of(context).brightness==Brightness.dark;return Scaffold(body:SafeArea(child:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(17,8,17,4),child:SizedBox(height:46,child:Stack(alignment:Alignment.center,children:[const Text('التقييمات',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900)),Align(alignment:Alignment.centerRight,child:IconButton(onPressed:()=>context.pop(),icon:const Icon(LucideIcons.arrowRight,size:22)))]))),Expanded(child:loading?const SpikeLoading():items.isEmpty?const SpikeEmptyState(message:'بعد استلام طلبك ستظهر المنتجات القابلة للتقييم هنا'):RefreshIndicator(onRefresh:_load,child:ListView.builder(padding:const EdgeInsets.fromLTRB(17,10,17,24),itemCount:items.length,itemBuilder:(context,i){final x=items[i];return Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:dark?spikeDarkPanel:spikePanel,borderRadius:BorderRadius.circular(20)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Container(width:42,height:42,decoration:BoxDecoration(color:Theme.of(context).colorScheme.surface,shape:BoxShape.circle),child:const Icon(LucideIcons.packageCheck,size:19)),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${x['product_name']??''}',style:const TextStyle(fontSize:13,fontWeight:FontWeight.w900)),Text('${x['store_name']??''}',style:const TextStyle(fontSize:10,color:spikeMuted))]))]),const SizedBox(height:10),Wrap(spacing:8,runSpacing:7,children:[if(x['can_review_product']==true)OutlinedButton.icon(onPressed:()=>_rate(store:false,item:x),icon:const Icon(Icons.star_outline_rounded,size:17),label:const Text('تقييم المنتج')),if(x['can_review_store']==true)OutlinedButton.icon(onPressed:()=>_rate(store:true,item:x),icon:const Icon(LucideIcons.store,size:16),label:const Text('تقييم المتجر'))]) ]));}))) ])));}}
