import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../app/providers.dart';
import '../../../core/theme.dart';
import '../../../core/widgets/async_state_widgets.dart';

class SupportChatScreen extends ConsumerStatefulWidget{const SupportChatScreen({super.key});@override ConsumerState<SupportChatScreen> createState()=>_SupportChatScreenState();}
class _SupportChatScreenState extends ConsumerState<SupportChatScreen>{final text=TextEditingController();String? threadId;List<Map<String,dynamic>> messages=[];bool loading=true,sending=false;
@override void initState(){super.initState();_load();}
@override void dispose(){text.dispose();super.dispose();}
Future<void> _load()async{setState(()=>loading=true);try{final repo=ref.read(engagementRepositoryProvider);threadId=await repo.ensureSupportThread();messages=await repo.supportMessages(threadId!);}catch(e){if(mounted)showSpikeToast(context,e.toString());}finally{if(mounted)setState(()=>loading=false);}}
Future<void> _send()async{final body=text.text.trim();if(body.isEmpty||threadId==null||sending)return;setState(()=>sending=true);try{await ref.read(engagementRepositoryProvider).sendSupportMessage(threadId!,body);text.clear();messages=await ref.read(engagementRepositoryProvider).supportMessages(threadId!);if(mounted)setState((){});}catch(e){if(mounted)showSpikeToast(context,e.toString());}finally{if(mounted)setState(()=>sending=false);}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(backgroundColor:Colors.transparent,title:const Text('خدمة العملاء'),centerTitle:true),body:loading?const SpikeLoading():Column(children:[Expanded(child:messages.isEmpty?const SpikeEmptyState(message:'ابدأ محادثتك مع الإدارة'):ListView.builder(reverse:false,padding:const EdgeInsets.all(17),itemCount:messages.length,itemBuilder:(context,i){final m=messages[i],mine='${m['sender_role']??''}'=='customer';return Align(alignment:mine?Alignment.centerRight:Alignment.centerLeft,child:Container(constraints:const BoxConstraints(maxWidth:290),margin:const EdgeInsets.only(bottom:8),padding:const EdgeInsets.symmetric(horizontal:12,vertical:10),decoration:BoxDecoration(color:mine?spikeRed:spikePanel,borderRadius:BorderRadius.circular(16)),child:Text('${m['body']??''}',style:TextStyle(color:mine?Colors.white:Colors.black)))));})),SafeArea(top:false,child:Padding(padding:const EdgeInsets.fromLTRB(12,8,12,12),child:Row(children:[Expanded(child:TextField(controller:text,minLines:1,maxLines:4,decoration:InputDecoration(hintText:'اكتب رسالتك...',filled:true,fillColor:spikeField,border:const OutlineInputBorder(borderSide:BorderSide.none,borderRadius:BorderRadius.all(Radius.circular(20)))))),const SizedBox(width:8),IconButton.filled(style:IconButton.styleFrom(backgroundColor:spikeRed),onPressed:sending?null:_send,icon:const Icon(Icons.send,color:Colors.white))])))]));}
