import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../app/providers.dart';
import '../../../core/settings/app_settings.dart';
import '../../../core/theme.dart';
import '../../../core/widgets/async_state_widgets.dart';
import '../../cart/data/cart_repository.dart';
import '../data/commerce_repository.dart';
class CheckoutScreen extends ConsumerStatefulWidget{const CheckoutScreen({super.key});@override ConsumerState<CheckoutScreen> createState()=>_CheckoutScreenState();}
class _CheckoutScreenState extends ConsumerState<CheckoutScreen>{CartSnapshot? cart;List<AddressModel> addresses=[];List<PaymentMethodModel> methods=[];List<CurrencyModel> currencies=[];AddressModel? address;PaymentMethodModel? payment;CurrencyModel? currency;DeliveryQuote? quote;bool loading=true,busy=false;
@override void initState(){super.initState();_load();}
Future<void> _load()async{setState(()=>loading=true);try{final cr=ref.read(commerceRepositoryProvider),preferred=ref.read(appSettingsProvider).currency;final results=await Future.wait([ref.read(cartRepositoryProvider).load(),cr.addresses(),cr.paymentMethods(),cr.currencies()]);cart=results[0] as CartSnapshot;addresses=results[1] as List<AddressModel>;methods=results[2] as List<PaymentMethodModel>;currencies=results[3] as List<CurrencyModel>;address=addresses.where((a)=>a.isActive).cast<AddressModel?>().firstOrNull??(addresses.isNotEmpty?addresses.first:null);payment=methods.isNotEmpty?methods.first:null;currency=currencies.where((c)=>c.code==preferred).cast<CurrencyModel?>().firstOrNull??currencies.where((c)=>c.code==(cart?.currencyCode??'USD')).cast<CurrencyModel?>().firstOrNull??(currencies.isNotEmpty?currencies.first:null);if(currency!=null){cart=await ref.read(cartRepositoryProvider).updateMeta(currencyCode:currency!.code);}if(address!=null&&cart!.items.isNotEmpty)quote=await cr.quote(addressId:address!.id,variantIds:cart!.items.map((e)=>e.variantId).toList());}catch(e){if(mounted)showSpikeToast(context,e.toString());}finally{if(mounted)setState(()=>loading=false);}}
Future<void> _chooseAddress()async{await context.push('/addresses');final list=await ref.read(commerceRepositoryProvider).addresses(),selected=list.where((a)=>a.isActive).cast<AddressModel?>().firstOrNull;if(selected!=null){setState(()=>address=selected);quote=await ref.read(commerceRepositoryProvider).quote(addressId:selected.id,variantIds:cart!.items.map((e)=>e.variantId).toList());if(mounted)setState((){});}}
Future<void> _currency(String? v)async{if(v==null)return;final x=currencies.where((c)=>c.code==v).firstOrNull;if(x==null)return;setState(()=>currency=x);await ref.read(appSettingsProvider.notifier).setCurrency(x.code);cart=await ref.read(cartRepositoryProvider).updateMeta(currencyCode:x.code);if(mounted)setState((){});}
Future<void> _submit()async{if(busy||cart==null||address==null||payment==null||currency==null)return;setState(()=>busy=true);try{final order=await ref.read(commerceRepositoryProvider).createOrder(cart:cart!,addressId:address!.id,paymentMethod:payment!.method,currencyCode:currency!.code);if(mounted){showSpikeToast(context,'تم إنشاء الطلب بنجاح');context.go('/order/${order.id}');}}catch(e){if(mounted)showSpikeToast(context,e.toString());}finally{if(mounted)setState(()=>busy=false);}}
@override Widget build(BuildContext context){if(loading)return const Scaffold(body:SpikeLoading());if(cart==null)return Scaffold(body:SpikeErrorState(onRetry:_load));final panel=Theme.of(context).brightness==Brightness.dark?spikeDarkPanel:spikePanel;return Scaffold(appBar:AppBar(title:const Text('تأكيد الطلب'),centerTitle:true),body:ListView(padding:const EdgeInsets.all(17),children:[_step(panel,'1','عنوان التوصيل',Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[TextButton(onPressed:_chooseAddress,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(address?.label??'اختر عنوان التوصيل',style:TextStyle(fontWeight:FontWeight.w800,color:Theme.of(context).colorScheme.onSurface)),Text(address?.addressLine??'مطلوب لحساب الشحن',style:const TextStyle(fontSize:11,color:Colors.grey))]))])),const SizedBox(height:10),_step(panel,'2','طريقة الدفع',Column(children:methods.map((m)=>RadioListTile<String>(contentPadding:EdgeInsets.zero,title:Text(m.label),subtitle:m.instructions.isEmpty?null:Text(m.instructions,style:const TextStyle(fontSize:10)),value:m.method,groupValue:payment?.method,onChanged:(_)=>setState(()=>payment=m))).toList())),const SizedBox(height:10),_step(panel,'3','العملة',DropdownButtonFormField<String>(value:currency?.code,items:currencies.map((c)=>DropdownMenuItem(value:c.code,child:Text('${c.name} (${c.code})'))).toList(),onChanged:_currency)),const SizedBox(height:10),Container(padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:panel,borderRadius:BorderRadius.circular(22)),child:Column(children:[_line('المنتجات','${cart!.subtotal.toStringAsFixed(2)} USD'),if(cart!.saving>0)_line('التوفير','- ${cart!.saving.toStringAsFixed(2)} USD'),_line('تقدير التوصيل',quote==null?'اختر العنوان':'${quote!.shippingYerOld.toStringAsFixed(2)} YER_OLD'),const Divider(),const Text('الإجمالي النهائي وسعر الصرف يُحسبان في الخادم عند إنشاء الطلب.',style:TextStyle(fontSize:10,color:Colors.grey))])),const SizedBox(height:16),SizedBox(height:50,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:spikeRed),onPressed:(address==null||payment==null||currency==null||cart!.items.isEmpty||busy)?null:_submit,child:busy?const SizedBox.square(dimension:20,child:CircularProgressIndicator(strokeWidth:2,color:Colors.white)):const Text('تأكيد وإنشاء الطلب')))]));}
Widget _step(Color panel,String n,String title,Widget child)=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:panel,borderRadius:BorderRadius.circular(22)),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Row(children:[CircleAvatar(radius:14,backgroundColor:spikeRed,child:Text(n,style:const TextStyle(color:Colors.white,fontSize:11))),const SizedBox(width:8),Text(title,style:const TextStyle(fontWeight:FontWeight.w800))]),const SizedBox(height:8),child]));Widget _line(String a,String b)=>Padding(padding:const EdgeInsets.symmetric(vertical:5),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(a),Text(b,style:const TextStyle(fontWeight:FontWeight.w800))]));}
extension _FirstOrNull<T> on Iterable<T>{T? get firstOrNull=>isEmpty?null:first;}
