import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:lucide_icons/lucide_icons.dart';
import '../../../app/providers.dart';
import '../../../core/theme.dart';
import '../../../core/widgets/async_state_widgets.dart';

class WalletScreen extends ConsumerStatefulWidget{const WalletScreen({super.key});@override ConsumerState<WalletScreen> createState()=>_WalletScreenState();}
class _WalletScreenState extends ConsumerState<WalletScreen>{Map<String,dynamic>? data;bool loading=true;String? error;
  @override void initState(){super.initState();_load();}
  Future<void> _load()async{setState(()=>loading=true);try{data=await ref.read(apiClientProvider).get('/wallet/me',auth:true);error=null;}catch(e){error=e.toString();}finally{if(mounted)setState(()=>loading=false);}}
  String _shortId(Object? value){final id='${value??''}';return id.length>8?id.substring(0,8):id;}
  @override Widget build(BuildContext context){if(loading)return const Scaffold(body:SpikeLoading());final d=data??const <String,dynamic>{},w=(d['wallet'] as Map?)??const {},tx=(d['transactions'] as List? ?? const []),purchases=(d['purchases'] as List? ?? const []),summary=(d['summary'] as Map?)??const {};return Scaffold(body:SafeArea(child:Column(children:[const _Head('محفظتي'),Expanded(child:error!=null?SpikeErrorState(message:error!,onRetry:_load):ListView(padding:const EdgeInsets.fromLTRB(17,0,17,24),children:[Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:Theme.of(context).brightness==Brightness.dark?spikeDarkPanel:Colors.white,borderRadius:BorderRadius.circular(24)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('الرصيد المتاح',style:TextStyle(fontSize:12)),const SizedBox(height:8),Text('\$${double.tryParse('${w['balance']??0}')?.toStringAsFixed(2)??'0.00'}',style:const TextStyle(fontSize:30,fontWeight:FontWeight.w800)),const SizedBox(height:8),const Text('رصيدك في Spike للمبالغ المستردة والرصيد المضاف والمشتريات المدعومة بالمحفظة.',style:TextStyle(fontSize:11,height:1.5))])),const SizedBox(height:12),Row(children:[Expanded(child:_stat('عدد المشتريات','${summary['orders_count']??0}')),const SizedBox(width:10),Expanded(child:_stat('إجمالي المشتريات','\$${double.tryParse('${summary['purchases_total']??0}')?.toStringAsFixed(2)??'0.00'}'))]),const SizedBox(height:18),const Text('آخر الحركات',style:TextStyle(fontSize:18,fontWeight:FontWeight.w700)),const SizedBox(height:10),if(tx.isEmpty)_empty('لا توجد حركات في المحفظة حتى الآن.')else...tx.whereType<Map>().map((x)=>_row('${x['note']??'حركة رصيد'}','${x['created_at']??''}','${x['direction']=='credit'?'+':'-'}\$${double.tryParse('${x['amount']??0}')?.toStringAsFixed(2)??'0.00'}')),const SizedBox(height:18),const Text('مشترياتي',style:TextStyle(fontSize:18,fontWeight:FontWeight.w700)),const SizedBox(height:10),if(purchases.isEmpty)_empty('لا توجد مشتريات حتى الآن.')else...purchases.whereType<Map>().take(8).map((x)=>_row('طلب #${_shortId(x['id'])}','${x['status']??''}','\$${double.tryParse('${x['total']??0}')?.toStringAsFixed(2)??'0.00'}'))]))]))]));}
  Widget _stat(String a,String b)=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:spikePanel,borderRadius:BorderRadius.circular(18)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:10)),const SizedBox(height:6),Text(b,style:const TextStyle(fontSize:14,fontWeight:FontWeight.w700))]));
  Widget _empty(String t)=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:spikePanel,borderRadius:BorderRadius.circular(18)),child:Text(t,style:const TextStyle(fontSize:11)));
  Widget _row(String title,String sub,String value)=>Container(margin:const EdgeInsets.only(bottom:8),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:spikePanel,borderRadius:BorderRadius.circular(18)),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w700)),const SizedBox(height:3),Text(sub,style:const TextStyle(fontSize:9,color:spikeMuted))])),Text(value,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w700))]));}

class VendorRegistrationScreen extends ConsumerStatefulWidget{const VendorRegistrationScreen({super.key});@override ConsumerState<VendorRegistrationScreen> createState()=>_VendorRegistrationScreenState();}
class _VendorRegistrationScreenState extends ConsumerState<VendorRegistrationScreen>{final name=TextEditingController(),phone=TextEditingController(),email=TextEditingController(),store=TextEditingController(),note=TextEditingController();bool busy=false;
  @override void initState(){super.initState();final u=ref.read(currentUserProvider).valueOrNull;if(u!=null){name.text='${u['name']??''}';phone.text='${u['phone']??''}';email.text='${u['email']??''}'.endsWith('@customer.spike.local')?'':'${u['email']??''}';}}
  @override void dispose(){name.dispose();phone.dispose();email.dispose();store.dispose();note.dispose();super.dispose();}
  Future<void> submit()async{if(name.text.trim().isEmpty||phone.text.trim().isEmpty||store.text.trim().isEmpty){showSpikeToast(context,'أكمل الحقول المطلوبة');return;}setState(()=>busy=true);try{await ref.read(apiClientProvider).post('/vendor-registration',data:{'applicant_name':name.text.trim(),'phone':phone.text.trim(),'email':email.text.trim(),'store_name':store.text.trim(),'note':note.text.trim()});if(mounted){showSpikeToast(context,'تم إرسال طلب التسجيل كتاجر');context.pop();}}catch(e){if(mounted)showSpikeToast(context,e.toString());}finally{if(mounted)setState(()=>busy=false);}}
  @override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Column(children:[const _Head('سجّل كتاجر'),Expanded(child:ListView(padding:const EdgeInsets.fromLTRB(17,0,17,24),children:[const Text('ابدأ البيع على Spike. أرسل بياناتك وسيتم مراجعة الطلب من الإدارة.',style:TextStyle(fontSize:12,height:1.6)),const SizedBox(height:16),_field(name,'الاسم الكامل',LucideIcons.user),const SizedBox(height:10),_field(phone,'رقم الجوال',LucideIcons.phone,keyboard:TextInputType.phone),const SizedBox(height:10),_field(email,'البريد الإلكتروني - اختياري',LucideIcons.mail,keyboard:TextInputType.emailAddress),const SizedBox(height:10),_field(store,'اسم المتجر',LucideIcons.store),const SizedBox(height:10),TextField(controller:note,maxLines:4,decoration:_dec('ملاحظة عن نشاط المتجر',LucideIcons.fileText)),const SizedBox(height:14),SizedBox(height:46,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:spikeRed,foregroundColor:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16))),onPressed:busy?null:submit,child:busy?const SizedBox.square(dimension:18,child:CircularProgressIndicator(strokeWidth:2,color:Colors.white)):const Text('إرسال طلب التسجيل',style:TextStyle(fontSize:12,fontWeight:FontWeight.w700))))]))])));
  Widget _field(TextEditingController c,String h,IconData i,{TextInputType? keyboard})=>SizedBox(height:54,child:TextField(controller:c,keyboardType:keyboard,decoration:_dec(h,i)));
  InputDecoration _dec(String h,IconData i)=>InputDecoration(hintText:h,filled:true,fillColor:Theme.of(context).brightness==Brightness.dark?spikeDarkPanel:Colors.white,border:OutlineInputBorder(borderSide:BorderSide.none,borderRadius:BorderRadius.circular(15)),suffixIcon:Icon(i,size:19),contentPadding:const EdgeInsets.symmetric(horizontal:16,vertical:14));}

class _Head extends StatelessWidget{const _Head(this.title);final String title;@override Widget build(BuildContext context){final dark=Theme.of(context).brightness==Brightness.dark;return Padding(padding:const EdgeInsets.fromLTRB(17,8,17,0),child:Column(children:[SizedBox(height:92,child:Stack(children:[Align(alignment:Alignment.centerRight,child:SizedBox(width:50,height:40,child:Material(color:dark?spikeDarkPanel:const Color(0xFFE8E8E8),borderRadius:BorderRadius.circular(22),child:InkWell(borderRadius:BorderRadius.circular(22),onTap:()=>context.canPop()?context.pop():context.go('/profile'),child:const Icon(LucideIcons.arrowRight,size:23)))))])),SizedBox(height:60,child:Align(alignment:Alignment.centerRight,child:Text(title,style:const TextStyle(fontSize:21,fontWeight:FontWeight.w700))))]));}}
