import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:image_picker/image_picker.dart';
import 'package:lucide_icons/lucide_icons.dart';
import '../../../app/providers.dart';
import '../../../core/theme.dart';
import '../../../core/widgets/async_state_widgets.dart';

class PersonalDataScreen extends ConsumerStatefulWidget{const PersonalDataScreen({super.key});@override ConsumerState<PersonalDataScreen> createState()=>_PersonalDataScreenState();}
class _PersonalDataScreenState extends ConsumerState<PersonalDataScreen>{final name=TextEditingController(),phone=TextEditingController(),code=TextEditingController();bool busy=false,otp=false,seeded=false;
@override void dispose(){name.dispose();phone.dispose();code.dispose();super.dispose();}
Future<void> _avatar()async{final x=await ImagePicker().pickImage(source:ImageSource.gallery,imageQuality:88,maxWidth:1600);if(x==null)return;setState(()=>busy=true);try{await ref.read(authRepositoryProvider).uploadAvatar(x.path);ref.invalidate(currentUserProvider);if(mounted)showSpikeToast(context,'تم تحديث الصورة');}catch(e){if(mounted)showSpikeToast(context,e.toString());}finally{if(mounted)setState(()=>busy=false);}}
Future<void> _saveName()async{if(name.text.trim().isEmpty)return;setState(()=>busy=true);try{await ref.read(authRepositoryProvider).updateProfile(name:name.text);ref.invalidate(currentUserProvider);if(mounted)showSpikeToast(context,'تم حفظ الاسم');}catch(e){if(mounted)showSpikeToast(context,e.toString());}finally{if(mounted)setState(()=>busy=false);}}
Future<void> _requestPhone()async{if(phone.text.trim().isEmpty)return;setState(()=>busy=true);try{await ref.read(authRepositoryProvider).requestPhoneChange(phone.text);if(mounted)setState(()=>otp=true);if(mounted)showSpikeToast(context,'تم إرسال رمز التحقق');}catch(e){if(mounted)showSpikeToast(context,e.toString());}finally{if(mounted)setState(()=>busy=false);}}
Future<void> _verifyPhone()async{if(code.text.trim().length!=6){showSpikeToast(context,'أدخل رمز التحقق المكوّن من 6 أرقام');return;}setState(()=>busy=true);try{await ref.read(authRepositoryProvider).verifyPhoneChange(code.text);ref.invalidate(currentUserProvider);if(mounted){setState(()=>otp=false);showSpikeToast(context,'تم تحديث رقم الجوال');}}catch(e){if(mounted)showSpikeToast(context,e.toString());}finally{if(mounted)setState(()=>busy=false);}}
@override Widget build(BuildContext context){final state=ref.watch(currentUserProvider),dark=Theme.of(context).brightness==Brightness.dark;return Scaffold(appBar:AppBar(title:const Text('الملف الشخصي'),centerTitle:true),body:state.when(loading:()=>const SpikeLoading(),error:(e,_)=>SpikeErrorState(message:e.toString(),onRetry:()=>ref.invalidate(currentUserProvider)),data:(u){if(u==null)return const SpikeEmptyState(message:'سجّل الدخول أولاً');if(!seeded){seeded=true;name.text='${u['name']??''}';phone.text='${u['phone']??''}';}final avatar='${u['avatar_url']??''}';return ListView(padding:const EdgeInsets.all(17),children:[Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:dark?spikeDarkPanel:spikePanel,borderRadius:BorderRadius.circular(24)),child:Column(children:[CircleAvatar(radius:38,backgroundColor:Colors.white,backgroundImage:avatar.isEmpty?null:CachedNetworkImageProvider(avatar),child:avatar.isEmpty?const Icon(LucideIcons.userRound,size:32):null),const SizedBox(height:8),TextButton.icon(onPressed:busy?null:_avatar,icon:const Icon(LucideIcons.camera,size:17),label:const Text('تغيير الصورة')),Text('${u['email']??''}',style:TextStyle(fontSize:11,color:dark?Colors.white60:Colors.black54))])),const SizedBox(height:14),const Text('الاسم',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:6),TextField(controller:name,decoration:_d(context,'الاسم الكامل')),const SizedBox(height:8),SizedBox(height:46,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:spikeRed),onPressed:busy?null:_saveName,child:const Text('حفظ الاسم'))),const SizedBox(height:20),const Text('رقم الجوال',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:6),TextField(controller:phone,keyboardType:TextInputType.phone,enabled:!otp,decoration:_d(context,'رقم الجوال الجديد')),const SizedBox(height:8),if(!otp)SizedBox(height:46,child:OutlinedButton.icon(onPressed:busy?null:_requestPhone,icon:const Icon(LucideIcons.send,size:18),label:const Text('إرسال رمز التحقق')))else...[TextField(controller:code,keyboardType:TextInputType.number,maxLength:6,decoration:_d(context,'رمز التحقق')),SizedBox(height:46,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:spikeRed),onPressed:busy?null:_verifyPhone,child:const Text('تأكيد الرقم'))),TextButton(onPressed:busy?null:_requestPhone,child:const Text('إعادة إرسال الرمز')),TextButton(onPressed:busy?null:()=>setState(()=>otp=false),child:const Text('تغيير الرقم'))]]); }));}
InputDecoration _d(BuildContext context,String h)=>InputDecoration(hintText:h,filled:true,fillColor:Theme.of(context).colorScheme.surfaceContainerHighest,border:const OutlineInputBorder(borderSide:BorderSide.none,borderRadius:BorderRadius.all(Radius.circular(18))));
}
