import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:lucide_icons/lucide_icons.dart';
import '../../../app/providers.dart';
import '../../../core/theme.dart';
import '../../../core/widgets/async_state_widgets.dart';

class PersonalDataScreen extends ConsumerStatefulWidget{const PersonalDataScreen({super.key});@override ConsumerState<PersonalDataScreen> createState()=>_PersonalDataScreenState();}
class _PersonalDataScreenState extends ConsumerState<PersonalDataScreen>{final name=TextEditingController(),phone=TextEditingController(),code=TextEditingController();bool busy=false,otp=false,seeded=false;
@override void dispose(){name.dispose();phone.dispose();code.dispose();super.dispose();}
Future<void> _saveName()async{if(name.text.trim().isEmpty)return;setState(()=>busy=true);try{await ref.read(authRepositoryProvider).updateProfile(name:name.text);ref.invalidate(currentUserProvider);if(mounted)showSpikeToast(context,'تم حفظ الاسم');}catch(e){if(mounted)showSpikeToast(context,e.toString());}finally{if(mounted)setState(()=>busy=false);}}
Future<void> _requestPhone()async{if(phone.text.trim().isEmpty)return;setState(()=>busy=true);try{await ref.read(authRepositoryProvider).requestPhoneChange(phone.text);if(mounted)setState(()=>otp=true);if(mounted)showSpikeToast(context,'تم إرسال رمز التحقق');}catch(e){if(mounted)showSpikeToast(context,e.toString());}finally{if(mounted)setState(()=>busy=false);}}
Future<void> _verifyPhone()async{if(code.text.trim().length!=6){showSpikeToast(context,'أدخل رمز التحقق المكوّن من 6 أرقام');return;}setState(()=>busy=true);try{await ref.read(authRepositoryProvider).verifyPhoneChange(code.text);ref.invalidate(currentUserProvider);if(mounted){setState(()=>otp=false);showSpikeToast(context,'تم تحديث رقم الجوال');}}catch(e){if(mounted)showSpikeToast(context,e.toString());}finally{if(mounted)setState(()=>busy=false);}}
@override Widget build(BuildContext context){final state=ref.watch(currentUserProvider);return Scaffold(appBar:AppBar(backgroundColor:Colors.transparent,title:const Text('الملف الشخصي'),centerTitle:true),body:state.when(loading:()=>const SpikeLoading(),error:(e,_)=>SpikeErrorState(message:e.toString(),onRetry:()=>ref.invalidate(currentUserProvider)),data:(u){if(u==null)return const SpikeEmptyState(message:'سجّل الدخول أولاً');if(!seeded){seeded=true;name.text='${u['name']??''}';phone.text='${u['phone']??''}';}return ListView(padding:const EdgeInsets.all(17),children:[Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:spikePanel,borderRadius:BorderRadius.circular(24)),child:Column(children:[const CircleAvatar(radius:34,child:Icon(LucideIcons.userRound,size:32)),const SizedBox(height:8),Text('${u['email']??''}',style:const TextStyle(fontSize:11,color:Colors.black54))])),const SizedBox(height:14),const Text('الاسم',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:6),TextField(controller:name,decoration:_d('الاسم الكامل')),const SizedBox(height:8),SizedBox(height:46,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:spikeRed),onPressed:busy?null:_saveName,child:const Text('حفظ الاسم'))),const SizedBox(height:20),const Text('رقم الجوال',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:6),TextField(controller:phone,keyboardType:TextInputType.phone,enabled:!otp,decoration:_d('رقم الجوال الجديد')),const SizedBox(height:8),if(!otp)SizedBox(height:46,child:OutlinedButton.icon(onPressed:busy?null:_requestPhone,icon:const Icon(LucideIcons.send,size:18),label:const Text('إرسال رمز التحقق')))else...[TextField(controller:code,keyboardType:TextInputType.number,maxLength:6,decoration:_d('رمز التحقق')),SizedBox(height:46,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:spikeRed),onPressed:busy?null:_verifyPhone,child:const Text('تأكيد الرقم'))),TextButton(onPressed:busy?null:_requestPhone,child:const Text('إعادة إرسال الرمز')),TextButton(onPressed:busy?null:()=>setState(()=>otp=false),child:const Text('تغيير الرقم'))]]); }));}
InputDecoration _d(String h)=>InputDecoration(hintText:h,filled:true,fillColor:spikeField,border:const OutlineInputBorder(borderSide:BorderSide.none,borderRadius:BorderRadius.all(Radius.circular(18))));
}
