import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:lucide_icons/lucide_icons.dart';
import '../../../app/providers.dart';
import '../../../core/settings/app_settings.dart';
import '../../../core/theme.dart';
import '../../../core/widgets/async_state_widgets.dart';
class SettingsScreen extends ConsumerWidget{const SettingsScreen({super.key});@override Widget build(BuildContext context,WidgetRef ref){final s=ref.watch(appSettingsProvider),ctrl=ref.read(appSettingsProvider.notifier),currencies=ref.watch(currenciesProvider),ar=s.language=='ar',dark=Theme.of(context).brightness==Brightness.dark;return Scaffold(body:SafeArea(child:Column(children:[Padding(padding:const EdgeInsets.fromLTRB(SpikeSpacing.page,SpikeSpacing.sm,SpikeSpacing.page,SpikeSpacing.xs),child:SizedBox(height:46,child:Stack(alignment:Alignment.center,children:[Text(ar?'الإعدادات المتقدمة':'Advanced settings',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900)),Align(alignment:Alignment.centerRight,child:IconButton(onPressed:()=>context.pop(),icon:const Icon(LucideIcons.arrowRight,size:22)))]))),Expanded(child:ListView(padding:SpikeSpacing.pageList,children:[_section(context,LucideIcons.sunMoon,ar?'المظهر':'Appearance',ar?'اختر مظهر التطبيق':'Choose app appearance',Column(children:[_row(context,ar?'الوضع الفاتح':'Light mode',LucideIcons.sun,s.themeMode==ThemeMode.light,()=>ctrl.setTheme(ThemeMode.light)),_row(context,ar?'الوضع الداكن':'Dark mode',LucideIcons.moon,s.themeMode==ThemeMode.dark,()=>ctrl.setTheme(ThemeMode.dark))])),const SizedBox(height:SpikeSpacing.md),_section(context,LucideIcons.languages,ar?'اللغة':'Language',ar?'لغة واجهة التطبيق':'App interface language',Column(children:[_row(context,'العربية',LucideIcons.languages,s.language=='ar',()=>ctrl.setLanguage('ar')),_row(context,'English',LucideIcons.languages,s.language=='en',()=>ctrl.setLanguage('en'))])),const SizedBox(height:SpikeSpacing.md),_section(context,LucideIcons.coins,ar?'العملة':'Currency',ar?'العملات المفعلة من النظام':'Backend-enabled currencies',currencies.when(loading:()=>const Padding(padding:EdgeInsets.all(SpikeSpacing.md),child:SpikeLoading()),error:(e,_)=>SpikeErrorState(message:e.toString(),onRetry:()=>ref.invalidate(currenciesProvider)),data:(items)=>Column(children:[for(final c in items)_row(context,'${c.name} (${c.code})',LucideIcons.banknote,s.currency==c.code,()=>ctrl.setCurrency(c.code))]))),const SizedBox(height:SpikeSpacing.lg),Container(padding:const EdgeInsets.all(SpikeSpacing.md),decoration:BoxDecoration(color:dark?spikeDarkPanel:spikePanel,borderRadius:BorderRadius.circular(SpikeRadius.control)),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[const Icon(LucideIcons.info,size:17,color:spikeMuted),const SizedBox(width:SpikeSpacing.sm),Expanded(child:Text(ar?'يتم حفظ اختياراتك على هذا الجهاز. العملة المختارة تُستخدم في الدفع وتبقى مرتبطة بالعملات المفعلة من الخادم.':'Your choices are saved on this device. Checkout uses the selected backend-enabled currency.',style:const TextStyle(fontSize:10,height:1.5,color:spikeMuted))) ]))]))])));}
Widget _section(BuildContext context,IconData icon,String title,String subtitle,Widget child){final dark=Theme.of(context).brightness==Brightness.dark;return Container(padding:const EdgeInsets.all(SpikeSpacing.lg),decoration:BoxDecoration(color:dark?spikeDarkPanel:spikePanel,borderRadius:BorderRadius.circular(SpikeRadius.card)),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Row(children:[Container(width:40,height:40,decoration:BoxDecoration(color:Theme.of(context).colorScheme.surface,shape:BoxShape.circle),child:Icon(icon,size:18)),const SizedBox(width:SpikeSpacing.md),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:15,fontWeight:FontWeight.w900)),const SizedBox(height:SpikeSpacing.xs),Text(subtitle,style:const TextStyle(fontSize:10,color:spikeMuted))]))]),const SizedBox(height:SpikeSpacing.sm),child]));}
Widget _row(BuildContext context,String title,IconData icon,bool selected,VoidCallback onTap)=>ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:0,vertical:SpikeSpacing.xs),onTap:onTap,leading:Icon(icon,size:19),title:Text(title,style:const TextStyle(fontSize:13,fontWeight:FontWeight.w700)),trailing:Icon(selected?Icons.radio_button_checked:Icons.radio_button_off,size:20,color:selected?spikeRed:spikeMuted));}
