import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../app/providers.dart';
import '../../../core/api_config.dart';
import '../../../core/theme.dart';
import '../../../core/widgets/async_state_widgets.dart';
import '../data/cart_repository.dart';

class CartScreen extends ConsumerStatefulWidget { const CartScreen({super.key}); @override ConsumerState<CartScreen> createState()=>_CartScreenState(); }
class _CartScreenState extends ConsumerState<CartScreen>{
  final _coupon=TextEditingController(); CartSnapshot? _cart; bool _loading=true;
  @override void initState(){super.initState();_load();}
  @override void dispose(){_coupon.dispose();super.dispose();}
  Future<void> _load() async{setState(()=>_loading=true);try{final c=await ref.read(cartRepositoryProvider).load();if(mounted)setState((){_cart=c;_coupon.text=c.couponCode??'';});}catch(e){if(mounted)showSpikeToast(context,e.toString());}finally{if(mounted)setState(()=>_loading=false);}}
  Future<void> _qty(CartItemModel item,int qty) async{try{final c=await ref.read(cartRepositoryProvider).update(variantId:item.variantId,quantity:qty);if(mounted)setState(()=>_cart=c);}catch(e){if(mounted)showSpikeToast(context,e.toString());}}
  String money(double v)=>'\$${v.toStringAsFixed(2)}';
  String _asset(String raw)=>raw.startsWith('/uploads/')?'${ApiConfig.assetBaseUrl}$raw':raw;
  void _openBanner(Map<String,dynamic> b){final type='${b['target_type']??''}',id='${b['target_id']??''}',url='${b['target_url']??''}';if(type=='product'&&id.isNotEmpty)context.push('/product/$id');else if(type=='category'&&id.isNotEmpty)context.push('/products?category=$id&title=المنتجات');else if(type=='collection'&&id.isNotEmpty)context.push('/products?collection=$id&title=المنتجات');else if(type=='store'&&id.isNotEmpty)context.push('/store/$id');else if(type=='internal'&&url.startsWith('/'))context.push(url);}
  Widget _banner(){final state=ref.watch(cartBannersProvider);return state.maybeWhen(data:(items){if(items.isEmpty)return const SizedBox.shrink();final b=items.first,src=_asset('${b['image_url']??''}');if(src.isEmpty)return const SizedBox.shrink();return Padding(padding:const EdgeInsets.only(bottom:10),child:InkWell(borderRadius:BorderRadius.circular(12),onTap:()=>_openBanner(b),child:ClipRRect(borderRadius:BorderRadius.circular(12),child:Stack(alignment:Alignment.bottomLeft,children:[Image.network(src,width:double.infinity,height:54,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const SizedBox.shrink()),if(b['countdown']==true&&b['ends_at']!=null)Positioned(left:7,bottom:7,child:StreamBuilder<int>(stream:Stream.periodic(const Duration(seconds:1),(i)=>i),builder:(_,__){final end=DateTime.tryParse('${b['ends_at']}');final d=end?.difference(DateTime.now());if(d==null||d.isNegative)return const SizedBox.shrink();final h=d.inHours,m=d.inMinutes.remainder(60),s=d.inSeconds.remainder(60);return Container(padding:const EdgeInsets.symmetric(horizontal:7,vertical:3),decoration:BoxDecoration(color:Colors.black87,borderRadius:BorderRadius.circular(8)),child:Text('${h.toString().padLeft(2,'0')}:${m.toString().padLeft(2,'0')}:${s.toString().padLeft(2,'0')}',style:const TextStyle(color:Colors.white,fontSize:10,fontWeight:FontWeight.w700)));}))]))));},orElse:()=>const SizedBox.shrink());}
  @override Widget build(BuildContext context){if(_loading)return const SafeArea(child:SpikeLoading());final cart=_cart;if(cart==null)return SafeArea(child:SpikeErrorState(onRetry:_load));if(cart.items.isEmpty)return SafeArea(child:Column(children:[const Expanded(child:SpikeEmptyState(message:'حقيبة التسوق فارغة')),Padding(padding:const EdgeInsets.all(17),child:SizedBox(width:double.infinity,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:spikeRed),onPressed:()=>context.go('/'),child:const Text('ابدأ التسوق'))))]));
    final groups=<String,List<CartItemModel>>{};for(final i in cart.items){(groups[i.storeName]??=[]).add(i);}return SafeArea(child:Column(children:[Expanded(child:ListView(padding:const EdgeInsets.all(17),children:[
      Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('حقيبة التسوق',style:TextStyle(fontSize:21,fontWeight:FontWeight.w800)),TextButton(onPressed:()=>context.push('/addresses'),child:const Text('اختر عنوان التوصيل'))]),_banner(),
      for(final e in groups.entries)...[Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:spikePanel,borderRadius:BorderRadius.circular(22)),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(e.key,style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:8),for(final item in e.value)Padding(padding:const EdgeInsets.symmetric(vertical:8),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[InkWell(onTap:()=>context.push('/product/${item.productId}'),child:Text(item.productName,maxLines:2,overflow:TextOverflow.ellipsis)),if(item.variantTitle.isNotEmpty)Text(item.variantTitle,style:const TextStyle(fontSize:10,color:Colors.black54)),Text(money(item.unitPrice),style:const TextStyle(fontWeight:FontWeight.w800))])),Row(children:[IconButton(onPressed:()=>_qty(item,item.quantity-1),icon:const Icon(Icons.remove_circle_outline)),Text('${item.quantity}'),IconButton(onPressed:item.quantity<item.stock?()=>_qty(item,item.quantity+1):null,icon:const Icon(Icons.add_circle_outline)),IconButton(onPressed:()=>_qty(item,0),icon:const Icon(Icons.delete_outline,color:spikeRed))])]))]))],
      Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:spikePanel,borderRadius:BorderRadius.circular(22)),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('لديك كوبون؟',style:TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:8),Row(children:[Expanded(child:TextField(controller:_coupon,decoration:const InputDecoration(hintText:'أدخل الكود',filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderSide:BorderSide.none)))),const SizedBox(width:8),FilledButton(style:FilledButton.styleFrom(backgroundColor:Colors.black),onPressed:()async{try{final c=await ref.read(cartRepositoryProvider).updateMeta(couponCode:_coupon.text);if(mounted){setState(()=>_cart=c);showSpikeToast(context,_coupon.text.trim().isEmpty?'تم إزالة الكوبون':'تم تطبيق الكوبون');}}catch(e){if(mounted)showSpikeToast(context,e.toString());}},child:const Text('تطبيق'))])])),const SizedBox(height:10),
      Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:spikePanel,borderRadius:BorderRadius.circular(22)),child:Column(children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('إجمالي المنتجات'),Text(money(cart.originalSubtotal))]),if(cart.saving>0)Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('الخصم'),Text('- ${money(cart.saving)}')]),const Divider(),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('المجموع قبل الشحن',style:TextStyle(fontWeight:FontWeight.w800)),Text(money(cart.subtotal),style:const TextStyle(fontWeight:FontWeight.w900))])]))
    ])),Padding(padding:const EdgeInsets.all(17),child:SizedBox(width:double.infinity,height:48,child:FilledButton(style:FilledButton.styleFrom(backgroundColor:spikeRed),onPressed:()=>context.push('/checkout'),child:Text('متابعة إلى الدفع • ${money(cart.subtotal)}'))))]));}
}
