import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:lucide_icons/lucide_icons.dart';
import '../../../app/providers.dart';
import '../../../core/theme.dart';
import '../../../core/widgets/async_state_widgets.dart';
import '../../../models/product.dart';
import '../../checkout/data/commerce_repository.dart';

class ProductDetailsScreen extends ConsumerStatefulWidget{const ProductDetailsScreen({super.key,required this.id});final String id;@override ConsumerState<ProductDetailsScreen>createState()=>_ProductDetailsScreenState();}
class _ProductDetailsScreenState extends ConsumerState<ProductDetailsScreen>{int _galleryIndex=0;String?_variantId;DeliveryQuote?_deliveryQuote;bool _quoting=false;String?_quotedAddressId,_quotedVariantId;
@override Widget build(BuildContext context){final state=ref.watch(productProvider(widget.id));return Scaffold(body:SafeArea(child:state.when(loading:()=>const SpikeLoading(),error:(e,_)=>SpikeErrorState(message:e.toString(),onRetry:()=>ref.invalidate(productProvider(widget.id))),data:(p)=>p==null?const SpikeEmptyState(message:'المنتج غير متاح حالياً'):_body(context,p))));}
Widget _body(BuildContext context,ProductModel product){final variants=product.variants;final selected=variants.firstWhere((v)=>v.id==_variantId,orElse:()=>product.cheapestVariant??(variants.isNotEmpty?variants.first:const ProductVariant(id:'',title:'',price:0,stock:0)));_variantId??=selected.id.isEmpty?null:selected.id;final images=product.images.isNotEmpty?product.images:[if(product.imageUrl!=null)product.imageUrl!];final old=selected.originalPrice,discount=old!=null&&old>selected.price&&selected.price>0?((old-selected.price)/old*100).round():0;final addresses=ref.watch(addressesProvider);return Stack(children:[ListView(padding:const EdgeInsets.only(bottom:96),children:[Stack(children:[SizedBox(height:350,child:PageView.builder(itemCount:images.isEmpty?1:images.length,onPageChanged:(i)=>setState(()=>_galleryIndex=i),itemBuilder:(_,i)=>Container(color:Colors.white,alignment:Alignment.center,child:images.isEmpty?const Icon(LucideIcons.image,size:60,color:Colors.black26):CachedNetworkImage(imageUrl:images[i],fit:BoxFit.contain,width:double.infinity,errorWidget:(_,__,___)=>const Icon(LucideIcons.image,size:60,color:Colors.black26)))),Positioned(top:10,right:14,child:_round(LucideIcons.arrowRight,()=>context.pop())),Positioned(top:10,left:14,child:_round(LucideIcons.heart,()async{try{await ref.read(engagementRepositoryProvider).addWishlist(product.id);if(context.mounted)showSpikeToast(context,'تمت إضافة المنتج إلى المفضلة');}catch(e){if(context.mounted)showSpikeToast(context,e.toString());}})),if(discount>0)Positioned(bottom:14,right:17,child:Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:5),decoration:BoxDecoration(color:spikeRed,borderRadius:BorderRadius.circular(13)),child:Text('-$discount%',style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w800))))]),if(images.length>1)Padding(padding:const EdgeInsets.only(top:8),child:Row(mainAxisAlignment:MainAxisAlignment.center,children:List.generate(images.length,(i)=>AnimatedContainer(duration:const Duration(milliseconds:180),width:i==_galleryIndex?17:7,height:7,margin:const EdgeInsets.symmetric(horizontal:2),decoration:BoxDecoration(borderRadius:BorderRadius.circular(5),color:i==_galleryIndex?Colors.black:Colors.black12))))),
_block(children:[if(product.storeId!=null)InkWell(onTap:()=>context.push('/store/${product.storeId}'),child:Row(children:[const Icon(LucideIcons.store,size:16),const SizedBox(width:6),Expanded(child:Text(product.storeName,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w700))),const Icon(LucideIcons.chevronLeft,size:16)])),if(product.storeId!=null)const SizedBox(height:10),Text(product.name,style:const TextStyle(fontSize:19,fontWeight:FontWeight.w800,height:1.45)),const SizedBox(height:8),Row(children:[const Icon(Icons.star_rounded,size:18,color:Color(0xFFF5B400)),const SizedBox(width:4),Text(product.reviewCount>0&&product.rating>0?product.rating.toStringAsFixed(1):'—',style:const TextStyle(fontWeight:FontWeight.w800)),if(product.reviewCount>0)Text('  (${product.reviewCount} تقييم)',style:const TextStyle(fontSize:11,color:spikeMuted))]),const SizedBox(height:12),Row(crossAxisAlignment:CrossAxisAlignment.end,children:[Text(_money(selected.price,selected.currency),style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900)),if(old!=null&&old>selected.price)...[const SizedBox(width:9),Text(_money(old,selected.currency),style:const TextStyle(fontSize:11,color:spikeRed,decoration:TextDecoration.lineThrough))]]),const SizedBox(height:9),Row(children:[Icon(selected.stock>0?LucideIcons.checkCircle2:LucideIcons.xCircle,size:16,color:selected.stock>0?Colors.green:spikeRed),const SizedBox(width:6),Text(selected.stock>0?'متوفر في المخزون':'غير متوفر حالياً',style:const TextStyle(fontSize:12,fontWeight:FontWeight.w600))])]),
if(variants.length>1)_block(children:[const Text('اختر الخيار',style:TextStyle(fontSize:14,fontWeight:FontWeight.w800)),const SizedBox(height:10),Wrap(spacing:8,runSpacing:8,children:variants.map((v)=>ChoiceChip(label:Text(v.title.isEmpty?_money(v.price,v.currency):v.title),selected:v.id==selected.id,onSelected:(_)=>setState((){_variantId=v.id;_deliveryQuote=null;_quotedVariantId=null;}))).toList())]),_deliveryBlock(context,addresses,selected),_block(children:[const Text('تفاصيل المنتج',style:TextStyle(fontSize:15,fontWeight:FontWeight.w800)),const SizedBox(height:9),Text((product.description??'').trim().isEmpty?'لا توجد تفاصيل إضافية لهذا المنتج حالياً.':product.description!,style:const TextStyle(fontSize:12,height:1.7)),if(product.returnable)const Padding(padding:EdgeInsets.only(top:10),child:Row(children:[Icon(LucideIcons.rotateCcw,size:16),SizedBox(width:7),Expanded(child:Text('هذا المنتج قابل للإرجاع حسب سياسة المتجر.',style:TextStyle(fontSize:11,fontWeight:FontWeight.w600))) ]))])]),Positioned(left:0,right:0,bottom:0,child:SafeArea(top:false,child:Container(padding:const EdgeInsets.fromLTRB(17,9,17,10),decoration:BoxDecoration(color:Theme.of(context).scaffoldBackgroundColor,border:const Border(top:BorderSide(color:Color(0x11000000)))),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisSize:MainAxisSize.min,children:[const Text('السعر',style:TextStyle(fontSize:9,color:spikeMuted)),Text(_money(selected.price,selected.currency),style:const TextStyle(fontSize:17,fontWeight:FontWeight.w900))])),SizedBox(height:48,child:FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:spikeRed,foregroundColor:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16))),onPressed:selected.id.isEmpty||selected.stock<=0?null:()async{try{await ref.read(cartRepositoryProvider).add(variantId:selected.id);if(context.mounted)showSpikeToast(context,'تمت إضافة المنتج إلى السلة');}catch(e){if(context.mounted)showSpikeToast(context,e.toString());}},icon:const Icon(LucideIcons.shoppingBag,size:18),label:Text(selected.stock<=0?'غير متوفر':'إضافة إلى السلة',style:const TextStyle(fontWeight:FontWeight.w800))))]))))]);}
Widget _round(IconData icon,VoidCallback onTap)=>Material(color:Colors.white,shape:const CircleBorder(),elevation:1,child:InkWell(onTap:onTap,customBorder:const CircleBorder(),child:SizedBox(width:39,height:39,child:Icon(icon,size:20,color:Colors.black))));
Widget _deliveryBlock(BuildContext context,AsyncValue<List<AddressModel>> addresses,ProductVariant selected)=>_block(children:[const Text('التوصيل',style:TextStyle(fontSize:14,fontWeight:FontWeight.w800)),const SizedBox(height:6),addresses.when(loading:()=>const LinearProgressIndicator(minHeight:2),error:(_,__)=>Row(children:[const Expanded(child:Text('أضف عنواناً لمعرفة تكلفة التوصيل.')),TextButton(onPressed:()=>context.push('/addresses'),child:const Text('العناوين'))]),data:(list){if(list.isEmpty)return ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(LucideIcons.mapPin,size:20),title:const Text('لا يوجد عنوان محفوظ'),trailing:TextButton(onPressed:()=>context.push('/address-form'),child:const Text('إضافة')));final active=list.firstWhere((a)=>a.isActive,orElse:()=>list.first),stale=_quotedAddressId!=active.id||_quotedVariantId!=selected.id;if(stale&&!_quoting&&selected.id.isNotEmpty)WidgetsBinding.instance.addPostFrameCallback((_)=>_loadQuote(active.id,selected.id));return Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(LucideIcons.mapPin,size:20),title:Text(active.label.isEmpty?active.cityName:active.label,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text('${active.cityName} • ${active.addressLine}',maxLines:1,overflow:TextOverflow.ellipsis),trailing:TextButton(onPressed:()=>context.push('/addresses'),child:const Text('تغيير'))),if(_quoting)const LinearProgressIndicator(minHeight:2),if(!_quoting&&_deliveryQuote!=null)Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Theme.of(context).colorScheme.surface,borderRadius:BorderRadius.circular(16)),child:Row(children:[const Icon(LucideIcons.truck,size:18),const SizedBox(width:8),const Expanded(child:Text('تكلفة التوصيل التقديرية')),Text('${_deliveryQuote!.shippingYerOld.round()} ر.ي قديم',style:const TextStyle(fontWeight:FontWeight.w800))]))]);})]);
Future<void>_loadQuote(String addressId,String variantId)async{if(_quoting)return;setState(()=>_quoting=true);try{final q=await ref.read(commerceRepositoryProvider).quote(addressId:addressId,variantIds:[variantId]);if(!mounted)return;setState((){_deliveryQuote=q;_quotedAddressId=addressId;_quotedVariantId=variantId;});}catch(_){if(!mounted)return;setState((){_deliveryQuote=null;_quotedAddressId=addressId;_quotedVariantId=variantId;});}finally{if(mounted)setState(()=>_quoting=false);}}
Widget _block({required List<Widget>children})=>Container(margin:const EdgeInsets.fromLTRB(17,10,17,0),padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Theme.of(context).brightness==Brightness.dark?spikeDarkPanel:spikePanel,borderRadius:BorderRadius.circular(22)),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:children));String _money(double amount,String currency){final c=currency.toUpperCase();if(c=='USD')return'\$${amount.toStringAsFixed(2)}';if(c=='SAR')return'${amount.toStringAsFixed(2)} ر.س';if(c.startsWith('YER'))return'${amount.round()} ر.ي';return'${amount.toStringAsFixed(2)} $c';}}
