import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import '../core/network/api_client.dart';
import '../core/storage/token_storage.dart';
import '../features/auth/data/auth_repository.dart';
import '../features/cart/data/cart_repository.dart';
import '../features/catalog/data/catalog_repository.dart';
import '../features/checkout/data/commerce_repository.dart';
import '../features/engagement/data/engagement_repository.dart';
import '../features/home/data/home_repository.dart';
import '../models/category.dart';
import '../models/product.dart';
import '../models/store.dart';

final secureStorageProvider=Provider<FlutterSecureStorage>((ref)=>const FlutterSecureStorage(aOptions:AndroidOptions(encryptedSharedPreferences:true)));
final tokenStorageProvider=Provider<TokenStorage>((ref)=>TokenStorage(ref.watch(secureStorageProvider)));
final apiClientProvider=Provider<ApiClient>((ref)=>ApiClient(tokenStorage:ref.watch(tokenStorageProvider)));
final authRepositoryProvider=Provider<AuthRepository>((ref)=>AuthRepository(ref.watch(apiClientProvider),ref.watch(tokenStorageProvider)));
final currentUserProvider=FutureProvider<Map<String,dynamic>?>((ref)=>ref.watch(authRepositoryProvider).me());
final homeRepositoryProvider=Provider<HomeRepository>((ref)=>HomeRepository(ref.watch(apiClientProvider)));
final homeDataProvider=FutureProvider<HomeData>((ref)=>ref.watch(homeRepositoryProvider).load());
final catalogRepositoryProvider=Provider<CatalogRepository>((ref)=>CatalogRepository(ref.watch(apiClientProvider)));
final categoriesProvider=FutureProvider<List<CategoryModel>>((ref)=>ref.watch(catalogRepositoryProvider).categories());
final productsProvider=FutureProvider.family<List<ProductModel>,(String?,String?)>((ref,q)=>ref.watch(catalogRepositoryProvider).products(categoryId:q.$1,collectionId:q.$2));
final productProvider=FutureProvider.family<ProductModel?,String>((ref,id)=>ref.watch(catalogRepositoryProvider).product(id));
final storesProvider=FutureProvider<List<StoreModel>>((ref)=>ref.watch(catalogRepositoryProvider).stores());
final allProductsProvider=FutureProvider<List<ProductModel>>((ref)=>ref.watch(catalogRepositoryProvider).products());
final cartRepositoryProvider=Provider<CartRepository>((ref)=>CartRepository(ref.watch(apiClientProvider)));
final engagementRepositoryProvider=Provider<EngagementRepository>((ref)=>EngagementRepository(ref.watch(apiClientProvider)));
final wishlistIdsProvider=FutureProvider<Set<String>>((ref)async=>(await ref.watch(engagementRepositoryProvider).wishlistIds()).toSet());
final favoritesProvider=FutureProvider<List<ProductModel>>((ref)async{final ids=await ref.watch(wishlistIdsProvider.future);final products=await ref.watch(allProductsProvider.future);return products.where((p)=>ids.contains(p.id)).toList();});
final commerceRepositoryProvider=Provider<CommerceRepository>((ref)=>CommerceRepository(ref.watch(apiClientProvider)));
final citiesProvider=FutureProvider<List<CityModel>>((ref)=>ref.watch(commerceRepositoryProvider).cities());
final addressesProvider=FutureProvider<List<AddressModel>>((ref)=>ref.watch(commerceRepositoryProvider).addresses());
final activeAddressProvider=Provider<AsyncValue<AddressModel?>>((ref){
  final addresses=ref.watch(addressesProvider);
  return addresses.whenData((list){
    if(list.isEmpty)return null;
    for(final address in list){if(address.isActive)return address;}
    return list.first;
  });
});
final paymentMethodsProvider=FutureProvider<List<PaymentMethodModel>>((ref)=>ref.watch(commerceRepositoryProvider).paymentMethods());
final currenciesProvider=FutureProvider<List<CurrencyModel>>((ref)=>ref.watch(commerceRepositoryProvider).currencies());
final ordersProvider=FutureProvider<List<OrderModel>>((ref)=>ref.watch(commerceRepositoryProvider).orders());
final orderDetailsProvider=FutureProvider.family<Map<String,dynamic>,String>((ref,id)=>ref.watch(commerceRepositoryProvider).orderDetails(id));
final orderTimelineProvider=FutureProvider.family<List<Map<String,dynamic>>,String>((ref,id)=>ref.watch(commerceRepositoryProvider).orderTimeline(id));
final returnsHistoryProvider=FutureProvider<List<Map<String,dynamic>>>((ref)=>ref.watch(commerceRepositoryProvider).returnsHistory());
final refundsHistoryProvider=FutureProvider<List<Map<String,dynamic>>>((ref)=>ref.watch(commerceRepositoryProvider).refundsHistory());
final cartBannersProvider=FutureProvider<List<Map<String,dynamic>>>((ref)=>ref.watch(commerceRepositoryProvider).cartBanners());
