import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:lucide_icons/lucide_icons.dart';
import '../../../app/providers.dart';
import '../../../core/theme.dart';
import '../../../core/widgets/async_state_widgets.dart';
import '../../checkout/data/commerce_repository.dart';

class OrdersScreen extends ConsumerWidget{const OrdersScreen({super.key});
@override Widget build(BuildContext context,WidgetRef ref){final state=ref.watch(ordersProvider);return Scaffold(appBar:AppBar(backgroundColor:Colors.transparent,title:const Text('طلباتي'),centerTitle:true),body:state.when(loading:()=>const SpikeLoading(),error:(e,_)=>SpikeErrorState(message:e.toString(),onRetry:()=>ref.invalidate(ordersProvider)),data:(orders){if(orders.isEmpty)return const SpikeEmptyState(message:'لا توجد طلبات حتى الآن');return ListView.builder(padding:const EdgeInsets.all(17),itemCount:orders.length,itemBuilder:(context,i){final o=orders[i];return Container(margin:const EdgeInsets.only(bottom:10),decoration:BoxDecoration(color:spikePanel,borderRadius:BorderRadius.circular(20)),child:ListTile(onTap:()=>context.push('/order/${o.id}'),leading:const CircleAvatar(child:Icon(LucideIcons.shoppingBag,size:20)),title:Text('طلب #${o.id.length>8?o.id.substring(0,8):o.id}',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${_status(o.status)} • ${o.paymentMethod=='cod'?'عند الاستلام':'حوالة'}',style:const TextStyle(fontSize:11)),trailing:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.end,children:[Text('${o.total.toStringAsFixed(2)} ${o.currencyCode}',style:const TextStyle(fontWeight:FontWeight.w900)),const Icon(Icons.arrow_back_ios_new,size:13)]));});}));}
String _status(String s)=>const {'pending_admin_review':'قيد مراجعة الإدارة','approved':'تمت الموافقة','processing':'قيد التجهيز','ready_for_delivery':'جاهز للتوصيل','with_courier':'مع المندوب','delivered':'تم التوصيل','rejected':'مرفوض'}[s]??s;
}

class OrderDetailsScreen extends ConsumerWidget{const OrderDetailsScreen({super.key,required this.id});final String id;
@override Widget build(BuildContext context,WidgetRef ref){final state=ref.watch(orderDetailsProvider(id));return Scaffold(appBar:AppBar(backgroundColor:Colors.transparent,title:const Text('تفاصيل الطلب'),centerTitle:true),body:state.when(loading:()=>const SpikeLoading(),error:(e,_)=>SpikeErrorState(message:e.toString(),onRetry:()=>ref.invalidate(orderDetailsProvider(id))),data:(d){final order=Map<String,dynamic>.from(d['order'] as Map? ?? const {});final subs=(d['suborders'] as List? ?? const []).whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();final items=(d['items'] as List? ?? const []).whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList();return ListView(padding:const EdgeInsets.all(17),children:[
  Container(padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:spikePanel,borderRadius:BorderRadius.circular(22)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('الحالة: ${order['status']??''}',style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:5),Text('الإجمالي: ${order['total']??0} ${order['currency_code']??''}',style:const TextStyle(fontWeight:FontWeight.w900)),Text('الدفع: ${order['payment_method']=='cod'?'عند الاستلام':'حوالة مالية'} • ${order['payment_status']??''}',style:const TextStyle(fontSize:11)),if(order['address_line']!=null)Text('التوصيل: ${order['address_line']}',style:const TextStyle(fontSize:11))])),const SizedBox(height:12),
  for(final s in subs)Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:spikePanel,borderRadius:BorderRadius.circular(20)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${s['store_name']??''}',style:const TextStyle(fontWeight:FontWeight.w800)),Text('الحالة: ${s['status']??''}',style:const TextStyle(fontSize:11)),if(s['shipping_total']!=null)Text('التوصيل: ${s['shipping_total']} ${s['currency_code']??''}',style:const TextStyle(fontSize:11))])),
  const Text('المنتجات',style:TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:8),for(final item in items)Container(margin:const EdgeInsets.only(bottom:8),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:spikePanel,borderRadius:BorderRadius.circular(18)),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${item['product_name']??''}',style:const TextStyle(fontWeight:FontWeight.w700)),Text('${item['store_name']??''} • ${item['variant_title']??''}',style:const TextStyle(fontSize:10,color:Colors.black54))])),Text('×${item['quantity']??1}')]))
]);}));}
}
