import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../app/providers.dart';
import '../../../core/theme.dart';
import '../../../core/widgets/async_state_widgets.dart';

class ReturnsRefundsScreen extends ConsumerWidget{const ReturnsRefundsScreen({super.key});
@override Widget build(BuildContext context,WidgetRef ref){final returns=ref.watch(returnsHistoryProvider),refunds=ref.watch(refundsHistoryProvider);return Scaffold(appBar:AppBar(backgroundColor:Colors.transparent,title:const Text('المرتجعات والاستردادات'),centerTitle:true),body:ListView(padding:const EdgeInsets.all(17),children:[const Text('المرتجعات',style:TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:8),returns.when(loading:()=>const SpikeLoading(),error:(e,_)=>SpikeErrorState(message:e.toString(),onRetry:()=>ref.invalidate(returnsHistoryProvider)),data:(items)=>items.isEmpty?const Padding(padding:EdgeInsets.symmetric(vertical:16),child:Text('لا توجد مرتجعات',style:TextStyle(color:Colors.black54))):Column(children:items.map((x)=>_card(title:'${x['product_name']??''}',subtitle:'${x['store_name']??''}',status:'${x['status']??''}',note:'${x['reason']??''}')).toList())),const SizedBox(height:18),const Text('الاستردادات',style:TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:8),refunds.when(loading:()=>const SpikeLoading(),error:(e,_)=>SpikeErrorState(message:e.toString(),onRetry:()=>ref.invalidate(refundsHistoryProvider)),data:(items)=>items.isEmpty?const Padding(padding:EdgeInsets.symmetric(vertical:16),child:Text('لا توجد مبالغ مستردة',style:TextStyle(color:Colors.black54))):Column(children:items.map((x)=>_card(title:'${x['product_name']??'استرداد مبلغ'}',subtitle:'${x['store_name']??''}',status:'${x['status']??''}',note:'${x['amount']??0} ${x['currency_code']??''}')).toList()))]));}
Widget _card({required String title,required String subtitle,required String status,required String note})=>Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(13),decoration:BoxDecoration(color:spikePanel,borderRadius:BorderRadius.circular(18)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(title,style:const TextStyle(fontWeight:FontWeight.w800))),Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:3),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(10)),child:Text(_status(status),style:const TextStyle(fontSize:10,fontWeight:FontWeight.w700)))]),if(subtitle.isNotEmpty)Padding(padding:const EdgeInsets.only(top:3),child:Text(subtitle,style:const TextStyle(fontSize:10,color:Colors.black54))),if(note.isNotEmpty)Padding(padding:const EdgeInsets.only(top:6),child:Text(note,style:const TextStyle(fontSize:11)))]));
String _status(String s)=>const {'pending':'قيد المعالجة','pending_admin_review':'قيد مراجعة الإدارة','approved':'معتمد','rejected':'مرفوض','paid':'تم إعادة المبلغ','returned':'مرتجع'}[s]??s;
}
